{{ config(
    materialized="table",
    partition_by={
        "field": "date_cohort",
        "data_type": "date",
        "granularity": "day"
    }
) }}

WITH unioned AS (
    SELECT
        contact_id,
        dougs_user_id,
        company_id,
        dougs_company_id,
        gender,
        age,
        eligible,
        legal_form,
        ape_code,
        activity,
        first_conversion_form,
        first_conversion_form_category,
        first_conversion_form_type,
        contact_category,
        lost_reason,
        contact_type,
        treatment_type,
        first_touchpoint_source_name,
        first_touchpoint_channel,
        first_form_source_name,
        first_form_channel,
        subscription_plan,
        CAST(NULL AS STRING) AS prestation_name,
        CAST(NULL AS STRING) AS prestation_category,
        CAST(NULL AS STRING) AS data_prestation_category,
        CASE
            WHEN calculation_type LIKE "%_by_lead_date" THEN date_lead
            WHEN calculation_type LIKE "%_by_mql_date" THEN date_mql
            WHEN calculation_type LIKE "%_by_won_invoicing_date" THEN date_won_invoicing
            WHEN calculation_type LIKE "%_by_won_creation_date" THEN date_won_creation
            WHEN calculation_type LIKE "%_by_won_accounting_date" THEN date_won_accounting
            WHEN calculation_type LIKE "%_by_lost_date" THEN date_lost
            WHEN calculation_type LIKE "%_by_reactivation_date" THEN LEAST(date_won_invoicing,date_won_creation,date_won_accounting)
        END AS date_cohort,
        CASE
            WHEN calculation_type LIKE "leads_by_%" THEN date_lead
            WHEN calculation_type LIKE "mqls_by_%" THEN date_mql
            WHEN calculation_type LIKE "clients_invoicing_by_%" THEN date_won_invoicing
            WHEN calculation_type LIKE "clients_creation_by_%" THEN date_won_creation
            WHEN calculation_type LIKE "clients_accounting_by_%" THEN date_won_accounting
            WHEN calculation_type LIKE "clients_direct_accounting_by_%" THEN date_won_accounting
            WHEN calculation_type LIKE "clients_invoicing_to_accounting_by_%" THEN date_won_accounting
            WHEN calculation_type LIKE "clients_crea_to_accounting_by_%" THEN date_won_invoicing
            WHEN calculation_type LIKE "losts_by_%" THEN date_lost
            WHEN calculation_type LIKE "reactivations_by_%" THEN LEAST(date_won_invoicing,date_won_creation,date_won_accounting)
        END AS date_actual,
        CASE WHEN calculation_type = "leads_by_lead_date" AND date_lead IS NOT NULL THEN 1 END AS leads_by_lead_date,
        CASE WHEN calculation_type = "mqls_by_lead_date" AND date_mql IS NOT NULL THEN 1 END AS mqls_by_lead_date,
        CASE WHEN calculation_type = "mqls_by_mql_date" AND date_mql IS NOT NULL THEN 1 END AS mqls_by_mql_date,
        -- CASE WHEN calculation_type = "clients_by_lead_date" AND date_won IS NOT NULL THEN 1 END AS clients_by_lead_date,
        -- CASE WHEN calculation_type = "clients_by_mql_date" AND date_won IS NOT NULL THEN 1 END AS clients_by_mql_date,
        -- CASE WHEN calculation_type = "clients_by_won_date" AND date_won IS NOT NULL THEN 1 END AS clients_by_won_date,
        CASE WHEN calculation_type = "clients_invoicing_by_lead_date" AND date_won_invoicing IS NOT NULL THEN 1 END AS clients_invoicing_by_lead_date,
        CASE WHEN calculation_type = "clients_invoicing_by_mql_date" AND date_won_invoicing IS NOT NULL THEN 1 END AS clients_invoicing_by_mql_date,
        CASE WHEN calculation_type = "clients_invoicing_by_won_invoicing_date" AND date_won_invoicing IS NOT NULL THEN 1 END AS clients_invoicing_by_won_date,
        CASE WHEN calculation_type = "clients_creation_by_lead_date" AND date_won_creation IS NOT NULL THEN 1 END AS clients_creation_by_lead_date,
        CASE WHEN calculation_type = "clients_creation_by_mql_date" AND date_won_creation IS NOT NULL THEN 1 END AS clients_creation_by_mql_date,
        CASE WHEN calculation_type = "clients_creation_by_won_creation_date" AND date_won_creation IS NOT NULL THEN 1 END AS clients_creation_by_won_date,
        CASE WHEN calculation_type = "clients_accounting_by_lead_date" AND date_won_accounting IS NOT NULL THEN 1 END AS clients_accounting_by_lead_date,
        CASE WHEN calculation_type = "clients_accounting_by_mql_date" AND date_won_accounting IS NOT NULL THEN 1 END AS clients_accounting_by_mql_date,
        CASE WHEN calculation_type = "clients_accounting_by_won_accounting_date" AND date_won_accounting IS NOT NULL THEN 1 END AS clients_accounting_by_won_date,
        CASE WHEN calculation_type = "clients_direct_accounting_by_lead_date" AND date_won_accounting IS NOT NULL AND (date_won_invoicing IS NULL OR date_won_invoicing > date_won_accounting) AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_direct_accounting_by_lead_date,
        CASE WHEN calculation_type = "clients_direct_accounting_by_mql_date" AND date_won_accounting IS NOT NULL AND (date_won_invoicing IS NULL OR date_won_invoicing > date_won_accounting) AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_direct_accounting_by_mql_date,
        CASE WHEN calculation_type = "clients_direct_accounting_by_won_accounting_date" AND date_won_accounting IS NOT NULL AND (date_won_invoicing IS NULL OR date_won_invoicing > date_won_accounting) AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_direct_accounting_by_won_date,
        CASE WHEN calculation_type = "clients_invoicing_to_accounting_by_lead_date" AND date_won_accounting IS NOT NULL AND date_won_invoicing < date_won_accounting AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_invoicing_to_accounting_by_lead_date,
        CASE WHEN calculation_type = "clients_invoicing_to_accounting_by_mql_date" AND date_won_accounting IS NOT NULL AND date_won_invoicing < date_won_accounting AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_invoicing_to_accounting_by_mql_date,
        CASE WHEN calculation_type = "clients_invoicing_to_accounting_by_won_accounting_date" AND date_won_accounting IS NOT NULL AND date_won_invoicing < date_won_accounting AND (date_won_creation IS NULL OR date_won_creation > date_won_accounting) THEN 1 END AS clients_invoicing_to_accounting_by_won_date,           
        CASE WHEN calculation_type = "clients_crea_to_accounting_by_lead_date" AND date_won_accounting IS NOT NULL AND date_won_creation < date_won_accounting THEN 1 END AS clients_crea_to_accounting_by_lead_date,
        CASE WHEN calculation_type = "clients_crea_to_accounting_by_mql_date" AND date_won_accounting IS NOT NULL AND date_won_creation < date_won_accounting THEN 1 END AS clients_crea_to_accounting_by_mql_date,
        CASE WHEN calculation_type = "clients_crea_to_accounting_by_won_accounting_date" AND date_won_accounting IS NOT NULL AND date_won_creation < date_won_accounting THEN 1 END AS clients_crea_to_accounting_by_won_date,                
        CASE WHEN calculation_type = "losts_by_lead_date" AND date_lost IS NOT NULL THEN 1 END AS losts_by_lead_date,
        CASE WHEN calculation_type = "losts_by_lost_date" AND date_lost IS NOT NULL THEN 1 END AS losts_by_lost_date,
        CASE WHEN calculation_type = "reactivations_by_reactivation_date" AND date_lost < LEAST(date_won_invoicing,date_won_creation,date_won_accounting) THEN 1 END AS reactivations_by_reactivation_date,
        CAST(NULL AS FLOAT64) AS prestation_amount,
        CAST(NULL AS INT64) AS impressions,
        CAST(NULL AS INT64) AS clicks,
        CAST(NULL AS FLOAT64) AS spend,
        CAST(NULL AS INT64) AS sessions
    FROM
        {{ ref('int_attributed_contact_revenues') }} 
    CROSS JOIN
        UNNEST(["leads_by_lead_date",
        "mqls_by_lead_date",
        "mqls_by_mql_date",
        "clients_invoicing_by_lead_date",
        "clients_invoicing_by_mql_date",
        "clients_invoicing_by_won_invoicing_date",
        "clients_creation_by_lead_date",
        "clients_creation_by_mql_date",
        "clients_creation_by_won_creation_date",
        "clients_accounting_by_lead_date",
        "clients_accounting_by_mql_date",
        "clients_accounting_by_won_accounting_date",
        "clients_direct_accounting_by_lead_date",
        "clients_direct_accounting_by_mql_date",
        "clients_direct_accounting_by_won_accounting_date",
        "clients_invoicing_to_accounting_by_lead_date",
        "clients_invoicing_to_accounting_by_mql_date",
        "clients_invoicing_to_accounting_by_won_accounting_date",
        "clients_crea_to_accounting_by_lead_date",
        "clients_crea_to_accounting_by_mql_date",
        "clients_crea_to_accounting_by_won_accounting_date",
        "losts_by_lead_date",
        "losts_by_lost_date",
        "reactivations_by_reactivation_date"]) AS calculation_type
    WHERE
        event_type IS NULL
        
    UNION ALL

    SELECT
        contact_id,
        dougs_user_id,
        company_id,
        dougs_company_id,
        gender,
        age,
        eligible,
        legal_form,
        ape_code,
        activity,
        first_conversion_form,
        first_conversion_form_category,
        first_conversion_form_type,
        contact_category,
        lost_reason,
        contact_type,
        treatment_type,
        first_touchpoint_source_name,
        first_touchpoint_channel,
        first_form_source_name,
        first_form_channel,
        subscription_plan,
        prestation_name,
        prestation_category,
        data_prestation_category,
        event_date AS date_cohort,
        event_date AS date_actual,
        CAST(NULL AS INT64) AS leads_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_won_date,
        CAST(NULL AS INT64) AS clients_creation_by_lead_date,
        CAST(NULL AS INT64) AS clients_creation_by_mql_date,
        CAST(NULL AS INT64) AS clients_creation_by_won_date,
        CAST(NULL AS INT64) AS clients_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS losts_by_lead_date,
        CAST(NULL AS INT64) AS losts_by_lost_date,
        CAST(NULL AS INT64) AS reactivations_by_reactivation_date,
        ROUND(prestation_amount,2) AS prestation_amount,
        CAST(NULL AS INT64) AS impressions,
        CAST(NULL AS INT64) AS clicks,
        CAST(NULL AS FLOAT64) AS spend,
        CAST(NULL AS INT64) AS sessions
    FROM
        {{ ref('int_attributed_contact_revenues') }} 
    WHERE
        event_type = 'prestation'    
  
    UNION ALL

    SELECT
        CAST(NULL AS STRING) AS contact_id,
        CAST(NULL AS STRING) AS dougs_user_id,
        CAST(NULL AS STRING) AS company_id,
        CAST(NULL AS STRING) AS dougs_company_id,
        CAST(NULL AS STRING) AS gender,
        CAST(NULL AS INT64) AS age,
        CAST(NULL AS BOOL) AS eligible,
        CAST(NULL AS STRING) AS legal_form,
        CAST(NULL AS STRING) AS ape_code,
        CAST(NULL AS STRING) AS activity,
        CAST(NULL AS STRING) AS first_conversion_form,
        CAST(NULL AS STRING) AS first_conversion_form_category,
        CAST(NULL AS STRING) AS first_conversion_form_type,
        CAST(NULL AS STRING) AS contact_category,
        CAST(NULL AS STRING) AS lost_reason,
        CAST(NULL AS STRING) AS contact_type,
        CAST(NULL AS STRING) AS treatment_type,
        source_name AS first_touchpoint_source_name,
        channel AS first_touchpoint_channel,
        source_name AS first_form_source_name,
        channel AS first_form_channel,
        CAST(NULL AS STRING) AS subscription_plan,
        CAST(NULL AS STRING) AS prestation_name,
        CAST(NULL AS STRING) AS prestation_category,
        CAST(NULL AS STRING) AS data_prestation_category,                
        date_report AS date_cohort,
        date_report AS date_actual,
        CAST(NULL AS INT64) AS leads_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_won_date,
        CAST(NULL AS INT64) AS clients_creation_by_lead_date,
        CAST(NULL AS INT64) AS clients_creation_by_mql_date,
        CAST(NULL AS INT64) AS clients_creation_by_won_date,
        CAST(NULL AS INT64) AS clients_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS losts_by_lead_date,
        CAST(NULL AS INT64) AS losts_by_lost_date,
        CAST(NULL AS INT64) AS reactivations_by_reactivation_date,        
        CAST(NULL AS FLOAT64) AS prestation_amount,
        impressions,
        clicks,
        spend,
        CAST(NULL AS INT64) AS sessions
    FROM
        {{ ref('int_advertising_statistics') }} 
  
    UNION ALL

    SELECT
        CAST(NULL AS STRING) contact_id,
        CAST(NULL AS STRING) dougs_user_id,
        CAST(NULL AS STRING) company_id,
        CAST(NULL AS STRING) dougs_company_id,
        CAST(NULL AS STRING) AS gender,
        CAST(NULL AS INT64) AS age,
        CAST(NULL AS BOOL) AS eligible,
        CAST(NULL AS STRING) AS legal_form,
        CAST(NULL AS STRING) AS ape_code,
        CAST(NULL AS STRING) AS activity,
        CAST(NULL AS STRING) AS first_conversion_form,
        CAST(NULL AS STRING) AS first_conversion_form_category,
        CAST(NULL AS STRING) AS first_conversion_form_type,
        CAST(NULL AS STRING) AS contact_category,
        CAST(NULL AS STRING) AS lost_reason,
        CAST(NULL AS STRING) AS contact_type,
        CAST(NULL AS STRING) AS treatment_type,
        session_source_name AS first_touchpoint_source_name,
        session_channel AS first_touchpoint_channel,
        session_source_name AS first_form_source_name,
        session_channel AS first_form_channel,
        CAST(NULL AS STRING) AS subscription_plan,
        CAST(NULL AS STRING) AS prestation_name,    
        CAST(NULL AS STRING) AS prestation_category,
        CAST(NULL AS STRING) AS data_prestation_category,            
        date_report AS date_cohort,
        date_report AS date_actual,
        CAST(NULL AS INT64) AS leads_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_lead_date,
        CAST(NULL AS INT64) AS mqls_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_by_won_date,
        CAST(NULL AS INT64) AS clients_creation_by_lead_date,
        CAST(NULL AS INT64) AS clients_creation_by_mql_date,
        CAST(NULL AS INT64) AS clients_creation_by_won_date,
        CAST(NULL AS INT64) AS clients_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_direct_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_invoicing_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_lead_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_mql_date,
        CAST(NULL AS INT64) AS clients_crea_to_accounting_by_won_date,
        CAST(NULL AS INT64) AS losts_by_lead_date,
        CAST(NULL AS INT64) AS losts_by_lost_date,
        CAST(NULL AS INT64) AS reactivations_by_reactivation_date,
        CAST(NULL AS FLOAT64) AS prestation_amount,
        CAST(NULL AS INT64) AS impressions,
        CAST(NULL AS INT64) AS clicks,
        CAST(NULL AS FLOAT64) AS spend,
        COUNT(DISTINCT session_id) AS sessions
    FROM
        {{ ref('int_google_analytics_4') }} 
    GROUP BY
        first_touchpoint_source_name,
        first_touchpoint_channel,
        first_form_source_name,
        first_form_channel,
        date_cohort,
        date_actual
),
final_layer AS (
    SELECT
        date_cohort,
        date_actual,
        gender,
        age,
        eligible,
        legal_form,
        ape_code,
        activity,
        first_conversion_form,
        first_conversion_form_category,
        first_conversion_form_type,
        contact_category,
        lost_reason,
        contact_type,
        treatment_type,
        first_touchpoint_source_name,
        first_touchpoint_channel,
        first_form_source_name,
        first_form_channel,
        subscription_plan,
        prestation_name,    
        prestation_category,
        data_prestation_category,
        SUM(leads_by_lead_date) AS leads_by_lead_date,
        SUM(mqls_by_lead_date) AS mqls_by_lead_date,
        SUM(mqls_by_mql_date) AS mqls_by_mql_date,
        SUM(clients_invoicing_by_lead_date)AS clients_invoicing_by_lead_date,
        SUM(clients_invoicing_by_mql_date)AS clients_invoicing_by_mql_date,
        SUM(clients_invoicing_by_won_date)AS clients_invoicing_by_won_date,
        SUM(clients_creation_by_lead_date)AS clients_creation_by_lead_date,
        SUM(clients_creation_by_mql_date)AS clients_creation_by_mql_date,
        SUM(clients_creation_by_won_date)AS clients_creation_by_won_date,
        SUM(clients_accounting_by_lead_date)AS clients_accounting_by_lead_date,
        SUM(clients_accounting_by_mql_date)AS clients_accounting_by_mql_date,
        SUM(clients_accounting_by_won_date)AS clients_accounting_by_won_date,
        SUM(clients_direct_accounting_by_lead_date)AS clients_direct_accounting_by_lead_date,
        SUM(clients_direct_accounting_by_mql_date)AS clients_direct_accounting_by_mql_date,
        SUM(clients_direct_accounting_by_won_date)AS clients_direct_accounting_by_won_date,
        SUM(clients_invoicing_to_accounting_by_lead_date)AS clients_invoicing_to_accounting_by_lead_date,
        SUM(clients_invoicing_to_accounting_by_mql_date)AS clients_invoicing_to_accounting_by_mql_date,
        SUM(clients_invoicing_to_accounting_by_won_date)AS clients_invoicing_to_accounting_by_won_date,
        SUM(clients_crea_to_accounting_by_lead_date)AS clients_crea_to_accounting_by_lead_date,
        SUM(clients_crea_to_accounting_by_mql_date)AS clients_crea_to_accounting_by_mql_date,
        SUM(clients_crea_to_accounting_by_won_date)AS clients_crea_to_accounting_by_won_date,
        SUM(losts_by_lead_date) AS losts_by_lead_date,
        SUM(losts_by_lost_date) AS losts_by_lost_date,
        SUM(reactivations_by_reactivation_date) AS reactivations_by_reactivation_date,
        SUM(prestation_amount) AS prestation_amount,
        SUM(impressions) AS impressions,
        SUM(clicks) AS clicks,
        SUM(spend) AS spend,
        SUM(sessions) AS sessions
    FROM
        unioned
    GROUP BY
        date_cohort,
        date_actual,
        gender,
        age,
        eligible,
        legal_form,
        ape_code,
        activity,
        first_conversion_form,
        first_conversion_form_category,
        first_conversion_form_type,
        contact_category,
        lost_reason,
        contact_type,
        treatment_type,
        first_touchpoint_source_name,
        first_touchpoint_channel,
        first_form_source_name,
        first_form_channel,
        subscription_plan,
        prestation_name,
        prestation_category,
        data_prestation_category          
)
SELECT * FROM final_layer WHERE date_cohort >= "2023-10-01"
