SELECT
    CAST(id AS STRING) AS hs_contact_id,
    CAST(properties_dougs_user_id AS STRING) AS dougs_user_id,
    properties_associatedcompanyid AS associated_company_id,
    NULLIF(REPLACE(TO_JSON_STRING(companies[0]) ,"\"", ""), 'null') AS company_1,
    NULLIF(REPLACE(TO_JSON_STRING(companies[1]) ,"\"", ""), 'null') AS company_2,
    NULLIF(REPLACE(TO_JSON_STRING(companies[2]) ,"\"", ""), 'null') AS company_3,
    createdAt AS created_at_timestamp,
    EXTRACT(DATE FROM createdAt) AS created_at,
    updatedAt AS updated_at_timestamp,
    EXTRACT(DATE FROM updatedAt) AS updated_at,
    properties_lastname AS last_name,
    properties_firstname AS first_name,
    properties_email AS email,
    properties_phone AS phone,
    properties_owner AS owner,
    properties_hubspot_owner_id AS owner_id,
    properties_eligible__ AS eligible,
    properties_hs_analytics_source AS original_source,
    properties_hs_object_source_label AS original_source_drill_down_1,
    EXTRACT(DATE FROM properties_first_conversion_date) AS first_conversion_date,
    IFNULL(properties_first_conversion_form, '-') AS first_conversion_form,
    IFNULL(properties_first_conversion_form_type, '-') AS first_conversion_form_type,
    IFNULL(properties_first_conversion_form_category, '-') AS first_conversion_form_category,
    IFNULL(properties_choix_de_pack, '-') AS pack_choice,
    properties_type_de_produit AS product_types,
    IFNULL(properties_lead_source, '-') AS lead_source,
    IFNULL(properties_hs_lead_status, '-') AS lead_status,
    IFNULL(properties_categorie_du_contact, '-') AS contact_category,
    properties_date_phase_de_saisie___lost___indesirable AS date_lost,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_lead) AS date_lead,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_marketingqualifiedlead) AS date_mql,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_salesqualifiedlead) AS date_sql,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_opportunity) AS date_opportunity,
    properties_date_premiere_facture_de_vente_finalisee AS date_won_invoicing,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_customer) AS date_won_accounting,
    EXTRACT(DATE FROM properties_hs_v2_date_entered_109588818) AS date_won_creation,
    _airbyte_extracted_at AS date_last_refresh
FROM {{ source('bronze_airbyte_hubspot', 'contacts') }}
